---
- name: Add PostgreSQL repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
  sudo: yes

- name: Add PostgreSQL repository key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  sudo: yes

- name: Update apt cache
  apt: update_cache=yes
  sudo: yes

- name: postgres
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-9.4
    - libpq-dev
    - python-psycopg2
  sudo: yes

- name: add user
  postgresql_user:
    name:  "{{ postgres_user }}"
    password: "{{ postgres_password }}"
    role_attr_flags: CREATEDB,NOSUPERUSER
  become: yes
  become_user: postgres
