default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: seq27_dev

test: &test
  <<: *default
  database: seq27_test

production:
  <<: *default
  database: seq27_prod

cucumber:
  <<: *test
