default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: seq27_dev

test: &test
  <<: *default
  database: seq27_test

production:
  <<: *default
  database: seq27_prod
  user: <%= ENV.fetch("PG_USER") %>
  password: <%= ENV.fetch("PG_PASSWORD") %>

cucumber:
  <<: *test
